name: Android CI

on:
  release:
    types: [published]
  push:
    branches:
      - master
#    tags:
#      - '3.*'
#  pull_request:
#    branches:
#      - master
#  watch:
#    types: [started]
#  schedule:
#    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 登录蓝奏云后查看cookie
      # LANZOU_ID ： woozooo.com -> Cookie -> ylogin
      # LANZOU_PSD ： pc.woozooo.com -> Cookie -> phpdisk_info
      LANZOU_ID: ${{ secrets.LANZOU_ID }}
      LANZOU_PSD: ${{ secrets.LANZOU_PSD }}
      # 蓝奏云里的文件夹名（需手动在蓝奏云创建）
      LANZOU_FOLDER: '阅读3测试版'
      # 是否上传到artifact
      UPLOAD_ARTIFACT: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Clear 18PlusList.txt
        run: |
          echo "清空18PlusList.txt"
          echo "">$GITHUB_WORKSPACE/app/src/main/assets/18PlusList.txt
      - name: App Minify
        if: ${{ github.event_name == 'release'}}
        run: |
          sed '/minifyEnabled/i\            shrinkResources true' $GITHUB_WORKSPACE/app/build.gradle -i
          sed 's/minifyEnabled false/minifyEnabled true/'         $GITHUB_WORKSPACE/app/build.gradle -i
      - name: Release Apk Sign
        run: |
          echo "给apk增加签名"
          cp $GITHUB_WORKSPACE/.github/workflows/legado.jks $GITHUB_WORKSPACE/app/legado.jks
          sed '$a\RELEASE_STORE_FILE=./legado.jks'          $GITHUB_WORKSPACE/gradle.properties -i
          sed '$a\RELEASE_KEY_ALIAS=legado'                 $GITHUB_WORKSPACE/gradle.properties -i
          sed '$a\RELEASE_STORE_PASSWORD=gedoor_legado'     $GITHUB_WORKSPACE/gradle.properties -i
          sed '$a\RELEASE_KEY_PASSWORD=gedoor_legado'       $GITHUB_WORKSPACE/gradle.properties -i
      - name: Apk Live Together
        run: |
          echo "设置apk共存"
          sed "s/'.release'/'.releaseA'/" $GITHUB_WORKSPACE/app/build.gradle  -i
          sed 's/.release/.releaseA/'     $GITHUB_WORKSPACE/app/google-services.json -i
      - name: Build With Gradle
        run: |
          echo "开始进行release构建"
          chmod +x gradlew
          ./gradlew assembleAppRelease
      - name: Upload App To Artifact
        if: ${{ env.UPLOAD_ARTIFACT != 'false' }}
        uses: actions/upload-artifact@v2
        with:
          name: legado apk
          path: ${{ github.workspace }}/app/build/outputs/apk/app/release/*.apk
      - name: Set Up Python 3
        if: ${{ env.LANZOU_PSD }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Dependence Install
        if: ${{ env.LANZOU_PSD }}
        run: |
          pip install requests
          pip install lanzou-api
      - name: Download Script
        if: ${{ env.LANZOU_PSD }}
        shell: python
        run: |
          import requests,os
          res = requests.get('https://raw.githubusercontent.com/Celeter/build/master/.github/scripts/API_lanzou.py')
          with open(os.environ["FILE_PATH"], 'wb') as f:
            f.write(res.content)
        env:
          FILE_PATH: ${{ github.workspace }}/.github/lzy.py
      - name: Upload App To Lanzou
        if: ${{ env.LANZOU_PSD }}
        run: python $GITHUB_WORKSPACE/.github/lzy.py
        env:
          UPLOAD_FOLDER: ${{ github.workspace }}/app/build/outputs/apk/app/release/
