name: Android CI

on: 
  release:
    types: [published]
  push:
    tags:
    - '3.*'
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: install git
      run: |
        sudo apt-get update
        sudo apt-get -y install git
    - name: clone code
      run: |
        git clone https://github.com/gedoor/legado.git /opt/legado
        echo "ojbk">/opt/legado/app/src/main/assets/18PlusList.txt
    - name: release apk sign
      run: |
        git clone https://github.com/10bits/gedoor-Build.git /opt/gedoor-Build
        cp /opt/gedoor-Build/.github/workflows/legado.jks /opt/legado/app/legado.jks
        sed '$a\RELEASE_STORE_FILE=./legado.jks' /opt/legado/gradle.properties -i 
        sed '$a\RELEASE_KEY_ALIAS=legado' /opt/legado/gradle.properties -i
        sed '$a\RELEASE_STORE_PASSWORD=gedoor_legado' /opt/legado/gradle.properties -i
        sed '$a\RELEASE_KEY_PASSWORD=gedoor_legado' /opt/legado/gradle.properties -i
    - name: Build with Gradle
      run: |
        cd /opt/legado
        chmod +x gradlew
        ./gradlew assembleRelease 
    - name : upload apk
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: legado apk
        path: /opt/legado/app/build/outputs/apk/app/release
